### ISSUE TITLE
Error in 3dsmax.ps1 causes render jobs to fail in Azure Batch

### ISSUE THREAD

**Issue by divgo** [Azure/batch-extension-templates#90]
In the PS Script, the following lines appear to be wrong and are throwing an error when submitting jobs through Azure Batch;

```
-- Pre render script
r = renderers.current
mversion = maxVersion()
rendererName = r as string
**r.system_vrayLog_level = 4
r.system_vrayLog_file = "D:\\batch\\tasks\\workitems\\ea3660-140_test01\\job-1\\0\\wd\\VRayLog.log"**
```

it appears that the correct setting values should be;

```
r.V_Ray_settings.system_vrayLog_level = 4
r.V_Ray_settings.system_vrayLog_file = "D:\\batch\\tasks\\workitems\\ea3660-140_test01\\job-1\\0\\wd\\VRayLog.log"
```

This DIFF seems to show that the setting was originally being set correctly, before this change;
https://github.com/Azure/batch-extension-templates/commit/bb92dce0740afe95aaeb271f65f71a3d80a8998e#diff-0afa87076f0964da5032b57ad4f48deb7ee49e630a93257282ab54f021c72a59

This is preventing us from running any Rendering Jobs using Azure Batch.

**Comment by divgo** [comment]
this is the error we are getting

```
2021/04/09 20:44:40 ERR: [05980] [06004] MAXScript FileIn Exception: -- Unknown property: "system_vrayLog_level" in V_Ray_GPU_5__hotfix_2:V_Ray_GPU_5__hotfix_2; Error occurred in anonymous codeblock; filename: D:\batch\tasks\workitems\ea3660-140_test01\job-1\0\wd\prerender.ms; position: 125; line: 5
```

**Comment by davidkydd** [comment]
Fixed in https://github.com/Azure/batch-extension-templates/commit/de8aadedb08dfb3da2c619c80b5ef1c477bf10bb

We actually removed VrayGPU from our CI testing some time ago because it was quite frequently failing to obtain a license (error appeared to be in chaosgroup bits, and was the motivation behind removing the switch which introduced this bug). 

Are you seeing this vray gpu 5 renderers succeed reliably now?
